services:
  - type: web
    name: quziar.github.io
    runtime: python
    repo: https://github.com/quziar/quziar.github.io
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --reload --host 0.0.0.0 --port 8000

  - type: worker
    name: quziar.github.io-worker
    runtime: python
    repo: https://github.com/quziar/quziar.github.io
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python worker.py
